# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:           'The Olive'
url:              http://kendrapierre.github.io/The-Olive/
baseurl:          /

github:
  repo:           https://github.com/KendraPierre/The-Olive

author:
  name:           'Data Studio 2016'
  url:            http://datastudio2016.datatherapy.org/
